### ISSUE TITLE
unexpected behavior of anchors with respect to lists

### ISSUE THREAD

**Issue by schreon** [yaml/pyyaml#130]
Hello,

I am trying to implement a yaml-loader which enables string interpolation as well as `for each` structures.

However, I am encountering unexpected behavior regarding anchors and lists.

Here is my python code:

```python
import re
import yaml
import logging

logger = logging.getLogger("yaml")


def constructor(*tags):
    def _my_decorator(method):
        for tag in tags:
            yaml.add_constructor(tag, method)
    return _my_decorator


def deep_replace(d, regex, value):

    if type(d) == str:
        return regex.sub(value, d)

    if type(d) == list:
        new_list = []
        for x in d:
            new_list.append(deep_replace(x, regex, value))
        return new_list

    if type(d) == dict:
        new_dict = {}
        for key, original_value in d.iteritems():
            key = deep_replace(key, regex, value)
            new_dict[key] = deep_replace(original_value, regex, value)

        return new_dict

    return d


@constructor("!scope")
def scope(loader, node):
    logger.debug("scope ...")
    scope = loader.construct_mapping(node, deep=True)
    proto_item = scope.pop("node")
    for variable, value in scope.iteritems():
        logger.debug("scope: %s -> %s" % (variable, value))
        regex = re.compile("\{\{\s*" + variable + "\s*\}\}")
        proto_item = deep_replace(proto_item, regex, str(value))

    return proto_item


@constructor("!for_each")
def for_each(loader, node):
    logger.debug("for each ...")
    tmp = loader.construct_mapping(node, deep=True)
    proto_item = tmp["node"]
    rng = tmp["range"]
    alias = tmp["alias"]

    logger.debug("for each %s in %s:" % (str(alias), str(rng)))

    regex = re.compile("\{\{\s*" + alias + "\s*\}\}")
    items = []
    for value in rng:
        item = deep_replace(proto_item, regex, str(value))
        items.append(item)

    return items


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)

    with open("bug.yaml", "r") as f:
        r = yaml.load(f.read())

    import json
    logger.debug("\n" + json.dumps(r, indent=4))
```

The according 'bug.yaml'  has the following contents:

```yaml
names: &names ["Alice", "Bob"]
alphabet: &alphabet "ABC"

items:
  !scope
  my_variable: 42
  node:
    - "{{ my_variable }}"

    - *alphabet

    - *names

    - some_key: X
      "{{ my_variable }}": "I can even interpolate variables in keys"

    - !for_each
      range: *alphabet
      alias: item
      node: "This is a letter: {{ item }}"

    - !for_each
      range: *names  # here, *names evaluates to [] instead of ["Alice", "Bob"]. Why?
      alias: item
      node: "Hello, {{ item }}!"

nested_items:
  one_deeper:
    !scope
    my_variable: 42
    node:
      - "{{ my_variable }}"

      - *alphabet

      - *names

      - !for_each
        range: *alphabet
        alias: item
        node: "This is a letter: {{ item }}"

      - !for_each
        range: *names  # here, *names correctly evaluates to ["Alice", "Bob"]. Why does it work in this case?
        alias: item
        node: "Hello, {{ item }}!"
```

And here is the unexpected output I get:

```
DEBUG:yaml:scope ...
DEBUG:yaml:for each ...
DEBUG:yaml:for each item in ABC:
DEBUG:yaml:for each ...
DEBUG:yaml:for each item in []:
DEBUG:yaml:scope: my_variable -> 42
DEBUG:yaml:scope ...
DEBUG:yaml:for each ...
DEBUG:yaml:for each item in ABC:
DEBUG:yaml:for each ...
DEBUG:yaml:for each item in ['Alice', 'Bob']:
DEBUG:yaml:scope: my_variable -> 42
DEBUG:yaml:
{
    "alphabet": "ABC", 
    "nested_items": {
        "one_deeper": [
            "42", 
            "ABC", 
            [
                "Alice", 
                "Bob"
            ], 
            [
                "This is a letter: A", 
                "This is a letter: B", 
                "This is a letter: C"
            ], 
            [
                "Hello, Alice!", 
                "Hello, Bob!"
            ]
        ]
    }, 
    "names": [
        "Alice", 
        "Bob"
    ], 
    "items": [
        "42", 
        "ABC", 
        [], 
        {
            "42": "I can even interpolate variables in keys", 
            "some_key": "X"
        }, 
        [
            "This is a letter: A", 
            "This is a letter: B", 
            "This is a letter: C"
        ], 
        []    <---- this should not be the empty list.
    ]
}
```

Look at "items" near the end of the logger output: `*names` is evaluated to an empty list, instead of `["Alice", "Bob"]`. I added an ASCII-Arrow at the corresponding line. Also, the debug logging output reads `DEBUG:yaml:for each item in []:`. 

I suspect the recursive calls of `deep_replace` are related to the source of trouble. However, I would not have expected that a list turns to an empty list. I would have understood a `None` value in case the recursive calls kick in before the parser had time to evaluate the anchors. But an empty list? Consierding that at the same time the anchor `alphabet: &alphabet "ABC"` (pointing to a string instead of a list) seems to be handled correctly. Also, nesting the dictionary in another dictionary seems to help; the corresponding output is exactly what I expected there.

What am I missing here? Is this behavior to be expected?

Any hints and comments are appreciated. Thank you very much.
