### ISSUE TITLE
yaml validation oddity

### ISSUE THREAD

**Issue by grinapo** [yaml/pyyaml#134]
I had some confusion with the proper syntax and had some test validated by various libraries. The weird result was that almost every library parsed it differently and some spew out validation error. This is the text, you may check whether your result is in sync with the specs (since I confess I didn't have the time to walk through it all). You're free to close the ticket if you don't need it.
```
grains:
  cluster: mine
  roles:
  - foo
  - bar
bluzze:
  cluster:
    mine
  roles:
    - foo
    - bar
zuggah:
  cluster:
    mi
   ne
  roles:
    - foo
     - bar
```
