### ISSUE TITLE
Incorrent list indentation with default_flow_style: false

### ISSUE THREAD

**Issue by ollycross** [yaml/pyyaml#135]
I am running pyyaml through the prettyyaml Sublime Text plugin (https://github.com/aukaost/SublimePrettyYAML).

I have some lists defined in my YAML with sloppy indentation: 

```
dependencies:
    enforced:
        module:
              - global_renewable_hub_cards
    module:
      - link
      - node
```

When I run pyyaml with `default_flow_style` set to `false` I expect the `-` preceding each list item to be one level of indentation down from their parent:

```
dependencies:
    enforced:
        module:
            - global_renewable_hub_cards
    module:
        - link
        - node
```

But the resulting file places them at the same level:
```
dependencies:
    enforced:
        module:
        - global_renewable_hub_cards
    module:
    - link
    - node
```

This fails validation with yamllint and (more importantly for me) Drupal's YAML validator until I manually correct the indentation.
