### ISSUE TITLE
Incorrect indentation with lists

### ISSUE THREAD

**Issue by bcoca** [yaml/pyyaml#234]
When using indentation this seems to be applied to the value of the list instead of to the list itself, as you can see below `indent=4` is applied after the leading `-` and not to the list itself.

```python
>>> print(yaml.dump(data['vars']['yaml'], indent=4, allow_unicode=True, default_flow_style=False))
list_of_dict_attr:
-   attr1: value1
    attr2: value2
    attr3:
    - item1
    - item2
single_attr: value1
>>> print(yaml.dump(data['vars']['yaml'], indent=2, allow_unicode=True, default_flow_style=False))
list_of_dict_attr:
- attr1: value1
  attr2: value2
  attr3:
  - item1
  - item2
single_attr: value1
```
original issue https://github.com/ansible/ansible/issues/48865

**Comment by ingydotnet** [comment]
@bcoca can you please check if this is in the Python code or if it's libyaml (or both)?

**Comment by sivel** [comment]
@ingydotnet Testing with `Dumper=yaml.Dumper` and `Dumper=yaml.CDumper` seems to produce the same result.

**Comment by ingydotnet** [comment]
Thanks @sivel. This will need to be fixed in both. Patches welcome :)

**Comment by zdog234** [comment]
It seems like the problem is occurring because `self.indention` is set to `False` in `Emitter` when `expect_block_sequence` is run, which makes the `self.increase_indent` code do nothing.

**Comment by DanyC97** [comment]
@zdog234 i've tried myself the below and didn't make any difference

```
    def expect_block_sequence(self):                  
        indentless = (self.mapping_context and not self.indention)
        self.increase_indent(flow=True, indentless=indentless)                  
        self.state = self.expect_first_block_sequence_item

```
or

```
    def expect_block_sequence(self):                  
        indentless = (self.mapping_context and not self.indention)
        self.increase_indent(flow=True)                  
        self.state = self.expect_first_block_sequence_item

```

**Comment by DanyC97** [comment]
@ingydotnet any chance you can shed some light and i may be able to fire a PR ?

**Comment by perlpunk** [comment]
Well, I wouldn't call that behaviour incorrect.
I guess it's a matter of taste, and I can find arguments proving that it's consistent.
What I'm also missing in this issue is the expected **correct** behaviour.

Let's look at both examples:
```
--- # spaces = 4
list_of_dict_attr:
-   attr1: value1
    attr2: value2
    attr3:
    - item1
    - item2
single_attr: value1
--- # spaces = 2
list_of_dict_attr:
- attr1: value1
  attr2: value2
  attr3:
  - item1
  - item2
single_attr: value1
```
The top level mapping has an indentation of zero (`0 * spaces`).
The value for `list_of_dict_attr`, the sequence, also has an indentation of zero, because PyYAML chooses zero-indented sequences always. That's why the dashes have no indentation in both cases. If it chooses zero-indentation, it simply does not depend on the number of spaces you configured.

The value of the first sequence item, the mapping `attr1: ...`, has an indentation of `1 * spaces` (respectively 4 or 2).
The sequence under `attr3` is zero-indented again, so `1 * spaces`. The items of this sequence are on the same line, so they don't get any indentation.

I **assume** you would expect this instead?
```
--- # spaces = 4
list_of_dict_attr:
  - attr1: value1
    attr2: value2
    attr3:
      - item1
      - item2
single_attr: value1
```

**Comment by kislyuk** [comment]
I can't speak for @DanyC97 but in my opinion yes, that last snippet is what is expected when passing `spaces=4`.

**Comment by pbasista** [comment]
From my point of view, the most widely-accepted indentation style for sequences is the one used multiple times in the official YAML specification. For instance, in [section 2.1](https://yaml.org/spec/1.2/spec.html#id2759963), example 2.3 looks like this:

```yaml
american:
  - Boston Red Sox
  - Detroit Tigers
  - New York Yankees
national:
  - New York Mets
  - Chicago Cubs
  - Atlanta Braves
```

The question is whether tools like `pyyaml` should render sequences in such a way for indentation of size 4 or for indentation of size 2.

I would argue that it seems incorrect to render sequences in such a way for indentation of size 4, because other items would visually appear to be indented more:

```yaml
mapping:
    one: 1
    two: 2
list:
  - 1
  - 2
```

Therefore, I think that it is more appropriate to render sequences in such a way for indentation of size 2:

```yaml
mapping:
  one: 1
  two: 2
list:
  - 1
  - 2
```

That being said, someone may prefer to *not* indent sequence items to a level that is visually similar to the indentation level of the other items. That is a fair requirement, but in order to fully support it, there would have to be a separate configuration option for indentation size of sequences.
