### ISSUE TITLE
executed by two times

### ISSUE THREAD

**Issue by Freakwill** [yaml/pyyaml#239]
I depend on yaml for storing data, and `pyyaml` is what I want.

Following is the code. When I run it (using yaml), I got an unwanted result. It seems that the file was executed two times according the output. But it is unable to explain the order of the output. It only happened when I used `yaml` in this case (with `__setstate__`). I am not sure that it is a problem of pyyaml or a bug of Python.

Could you explain it and help me?

output (in the very order):
> start loading start loading end 3 end 3

If I print the quotes, then they will be printed two times, in the given order.

```python
    # -*- coding: utf-8 -*-
    
    class Quote(object):
        """Quotes of famous peaple"""
        
        __slots__ = ('content', 'topic', 'author', 'info')
    
        def __init__(self, content='', topic='', author='', info=''):
            """
                content {str} -- [content of the quote] (default: {''})
                topic {str} -- [topic of the quote] (default: {''})
                author {str} -- [the author] (default: {''})
                info {str} -- related information (default: {''})
            """
            self.content = content
            self.topic = topic
            self.author = author
            self.info = info
    
        def __str__(self):
            return '{0:tight}'.format(self)
    
        def __format__(self, spec):
            if spec == 'signature':
                return ('--- ' + self.author).rjust(len(self.content))
            elif spec == 'tight':
                return '{0.content} --- {0.author}'.format(self)
            else:
                L = len(self.content)
                return '{0:content}\n{0:signature}'.format(self)
    
        def __getstate__(self):
            return self.content, self.topic, self.author, self.info
    
        def __setstate__(self, state):
            if isinstance(state, dict):
                for prop in Quote.__slots__:
                    setattr(self, prop, state.get(prop, ""))
            else:
                self.content, self.topic, self.author, self.info = state
    
        @staticmethod
        def read_yaml(fname, topic=None):
            print('loading')
            with open(fname) as fo:
                quotes = yaml.load(fo)
            return quotes
    
    print('start')
    import yaml
    quotes = Quote.read_yaml('../quotes.yaml')
    print('end')
    print(len(quotes))
```
Following is the yaml file that could be parsed successively.
```yaml
    - !!python/object:pybrainyquote.Quote
      content: >
        No one has ever read a book, only one in the book to read themselves, to find themselves or to check their own.
      topic: Unknown
      author: Roman Rollan
    
    
    - !!python/object:pybrainyquote.Quote
      content: Je pense, donc je suis.
      topic: Science
      author: Rene Descartes
    
    
    - !!python/object:pybrainyquote.Quote
      content: >
        To show off what he needed anything; hide anything, what self-esteem. 
        The so-called normal people, good people just self-defense. The real mental health, is defenseless without victimization.
      topic: Personality
      author: Unknown 
```
