### ISSUE TITLE
Anchor injection does not work in .load

### ISSUE THREAD

**Issue by psarka** [yaml/pyyaml#249]
Consider the following `test.yaml` file:

```yaml
foo: &anchor
  K1: "One"
  K2: "Two"

bar:
  <<: *anchor
  K2: "Deuce"
  K3: "Three"
```

The call `yaml.safe_load(open('test.yaml'))` loads it successfully and returns an expected object:
```python
{'foo': {'K1': 'One', 'K2': 'Two'},
 'bar': {'K1': 'One', 'K2': 'Deuce', 'K3': 'Three'}}
```

The call `yaml.load(open('test.yaml'))`, however, crashes with an exception:

```
ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:merge'
  in "test.yaml", line 6, column 3
```

I would expect it to also succeed.
