### ISSUE TITLE
Starting value with double quotes at the begining

### ISSUE THREAD

**Issue by vrst37** [yaml/pyyaml#307]
Hello,

I want to dump the following yaml file using this module:

```
network:
  renderer: NetworkManager
  version: 2
  wifis:
    wlp58s0:
      access-points:
        "apn":
          password: "pwd"
```

Notice the double quotes aroudn apn and pwd.

Now I have tried to do this using escape characters, and a few other tricks, and I am unable to do this.

import yaml

```
d = {
    'network': {
        'version': 2,
        'renderer': 'NetworkManager',
        'wifis': {
            'wlp58s0': {
                'access-points': {
                    'apn': {
                        'password': 'pwd'
                    }
                }
            }
        }
    }
}

with open('/home/edyza/result.yml', 'w') as yaml_file:
    yaml.dump(d, yaml_file, default_flow_style=False, default_style=None)

```
But I get the following:

```
network:
  renderer: NetworkManager
  version: 2
  wifis:
    wlp58s0:
      access-points:
        apn:
          password: pwd
```

When I try:

```
import yaml

d = {
    'network': {
        'version': 2,
        'renderer': 'NetworkManager',
        'wifis': {
            'wlp58s0': {
                'access-points': {
                    '"apn"': {
                        'password': "\"pwd\""
                    }
                }
            }
        }
    }
}

with open('/home/edyza/result.yml', 'w') as yaml_file:
    yaml.dump(d, yaml_file, default_flow_style=False, default_style=None)

```

I get 
```
network:
  renderer: NetworkManager
  version: 2
  wifis:
    wlp58s0:
      access-points:
        '"apn"':
          password: '"pwd"'
```

How to achieve this?

SO Link [here](https://stackoverflow.com/questions/56694257/generate-yaml-file-from-python-with-certain-keys-and-values-with-double-quotes)
