### ISSUE TITLE
dump error 

### ISSUE THREAD

**Issue by whiteskylife** [yaml/pyyaml#331]
this is my code:

```
import yaml
target_file = open('result.yaml','w',encoding='utf-8')

s_content = """
login-provider:
    k8s:
        helm_template_name: zhenai-crm-demo-provider
        livenessProbe:
          tcpSocket:
            port: 5089
        readinessProbe:
          tcpSocket:
            port: 5089
        
"""

content = yaml.load(s_content, Loader=yaml.FullLoader)
content['login-provider']['k8s']['new_arg'] = content['login-provider']['k8s']['readinessProbe']

print(content)
yaml.dump(content, target_file)
```

output is OK like this:
```
{'login-provider': {'k8s': {'helm_template_name': 'zhenai-crm-demo-provider', 'livenessProbe': {'tcpSocket': {'port': 5089}}, 'readinessProbe': {'tcpSocket': {'port': 5089}}, 'new_arg': {'tcpSocket': {'port': 5089}}}}}
```
but the result.yaml is terrible：
```
login-provider:
  k8s:
    helm_template_name: zhenai-crm-demo-provider
    livenessProbe:
      tcpSocket:
        port: 5089
    new_arg: &id001
      tcpSocket:
        port: 5089
    readinessProbe: *id001
```

“&id001” and “*id001” is not the result I want，pls help me ，thx
