### ISSUE TITLE
Could I specify a prefix and load to a class instance?

### ISSUE THREAD

**Issue by fy-kenny** [yaml/pyyaml#342]
```yaml
a:
  b:
     c:
        d: xxxx
        e: yyyyy
              f: nnnnn
              g: mmmm
```
#####
I come from java. so could I use it like java AutoConfiguration
```python
class YamlConfig(prefix="a.b.c"):
.....
```

#####
```python
yamlConfig = YamlConifg()

yamlConfig = yaml.load()
or yaml.load(yamlConifg)
or yamlConfig = yaml.load(YamlConfig.class)
```
#####
And then I can use like this:
```python
yamlConfig.d
or yamlConfig.e()
or yamlConfig.e.f
or yamlConfig.e().f()
or yamlConifg.e.f()
```
###
**Could you tell me you have already been implemented like this? And how can I found the docuemnt? or detail examples ,  or which version?**
