### ISSUE TITLE
String Formating with Anchor References

### ISSUE THREAD

**Issue by q4Zar** [yaml/pyyaml#353]
I'm trying to combine functionnalities and avoid hardcoding things but i can't find solutions so i'm asking here.

Example talks better than words :

```yaml

master_grid:
  
  values:
    default:        &vd       100/34
    default-gtc:    &dvgtc    "repeat(34, {{*vd}})"

```
then loading :

```python
with open('./psych_datamodel.yml', 'r') as yml:
  data_model = yaml.load(yml, Loader=yaml.FullLoader)
```

the result is obviously 

```python
{'master_grid': {'styles': {'template': {'display': 'grid'}},
                 'values': {'default': '100/34',
                 'default-gtc': 'repeat(34, {{*vd}})'}}}
```

When i'm looking to have a result like 

```python
{'master_grid': {'styles': {'template': {'display': 'grid'}},
                 'values': {'default': '100/34',
                 'default-gtc': 'repeat(34, {{2.9411764705882355}})'}}}
```

where *vd = 100/34 = 2.9411764705882355

Do someone can orientate me through a possible solutions to do that natively with yaml ? 
Or do i need to use another layer like Jinja ...

Thanks for listening and see you soon!
