### ISSUE TITLE
yaml.dump appends a line at the end of the file

### ISSUE THREAD

**Issue by NargiT** [yaml/pyyaml#381]
Hello,

`yaml.dump()` adds a new line at the end of a file. here an example to illustrate my problem.

test.yaml

```yaml
foo:
  bar: hello
  loul: world
```
No new line after `loul: world`

```python
from pathlib import Path

import yaml

def read_text():
    with open("test.yaml") as file:
        data = yaml.safe_load(file)
    
    with open("test2.yaml", mode="w") as file:
        yaml.safe_dump(data, file, default_flow_style=False, sort_keys=False)

    file_text = Path("test.yaml").read_text()
    new_file_text = Path("test2.yaml").read_text()
    
    assert file_text == new_file_text
    # Raise AssertionError

if __name__ == '__main__':
    read_text()
```

test2.yaml
```yaml
foo:
  bar: hello
  loul: world
# this line is added
```

Is this correct ?
