### ISSUE TITLE
Dump adds unnecessary line break

### ISSUE THREAD

**Issue by sausageRoll** [yaml/pyyaml#463]
```
import yaml

def main():
    document = open("temp.yaml", "r")
    load = yaml.safe_load(document.read())

    print(yaml.dump(load))
```

temp.yaml:
```
logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%-5level [%X{Request-Tracker}] [%date{ISO8601}] [%thread]: %c:%method:%line- %msg%n"
      timeZone: UTC
```

Expected result:
```
logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%-5level [%X{Request-Tracker}] [%date{ISO8601}] [%thread]: %c:%method:%line- %msg%n"
      timeZone: UTC
```

Actual result:
```
logging:
  appenders:
  - logFormat: '%-5level [%X{Request-Tracker}] [%date{ISO8601}] [%thread]: %c:%method:%line-
      %msg%n'
    timeZone: UTC
    type: console
  level: INFO
```

Please notice unnecessary line break for `logFormat`
