### ISSUE TITLE
move binary parts to beginning?

### ISSUE THREAD

**Issue by allefeld** [yaml/pyyaml#484]
YAML supports binary data using the `!!binary` tag, which makes it useful as a serialization format for arbitrary objects including e.g. NumPy arrays. On the other hand, YAML is supposed to be human-readable. If there are one or more large arrays in the dumped data, the actually human-readable parts can be separated by long stretches of base64-encoded data, making it very hard to get an overview and find the relevant parts in a text editor.

That could be resolved by putting encoded binary data not in its place in the data hierarchy, but at the end, using anchors and aliases to reference it in the right place. – Ok, reading the [specification](https://yaml.org/spec/1.2/spec.html#id2765878) I realize that aliases can only reference previous anchors, so the binary parts would actually have to be put at the beginning. That is less nice, but would still improve human-readability.

Another problem is that the anchor / alias mechanism is meant to create multiple references to the same data, so the serialized form would no longer 1:1 correspond to the data being serialized but have additional elements. I'm guessing that could be resolved by adopting a name convention similar to Python's prefixed `_`. After deserialization, such elements are removed.

Of course that whole behavior would be optional.

A sketch of what I think of: Change

````
a:
  b: 12
  c: Hello
  d:
    - 23
    - !!binary |
      AAAAAAAAAAB7FK5H4XqEP3sUrkfhepQ/uB6F61G4nj97FK5H4XqkP5qZmZmZmak/uB6F61G4rj/s
      ...
      UbgeheuxP3sUrkfherQ/CtejcD0Ktz+amZmZmZm5Pylcj8L1KLw/uB6F61G4vj+kcD0K16PAP+xR
  e: World
f: 42
````

to

````
_bin1: &bin1
  !!binary |
  AAAAAAAAAAB7FK5H4XqEP3sUrkfhepQ/uB6F61G4nj97FK5H4XqkP5qZmZmZmak/uB6F61G4rj/s
  ...
  UbgeheuxP3sUrkfherQ/CtejcD0Ktz+amZmZmZm5Pylcj8L1KLw/uB6F61G4vj+kcD0K16PAP+xR
a:
  b: 12
  c: Hello
  d:
    - 23
    - *bin1
  e: World
f: 42
````

If one opens this in an editor, simply jumping to the end reveals the human-readable part. Or on the command line, `tail` could do the trick.
