### ISSUE TITLE
flow style and line split

### ISSUE THREAD

**Issue by jimy-byerley** [yaml/pyyaml#485]
Hello dear developpers,
I'm using the `default_flow_style=None` setting to save space in my config file (I'm dumping a lot of vector in my config).
However it seems that the dumper makes strange choices on when to dump in flow and when in block.
It leads to situations like this:

```yaml
primitives:
    curve_resolution: {type: rad, seg: 0.19634954084936207}
scene: {debug_faces: false, debug_groups: false,
    debug_points: false, display_annotations: true,
    display_faces: true, display_grid: true,
    display_groups: true, display_points: false,
    display_wire: false, projection: Perspective,
    surface_shading: true}
```

expected behavior:
```yaml
primitives:
    curve_resolution: {type: rad, seg: 0.19634954084936207}
scene: 
    debug_faces: false
    debug_groups: false
    debug_points: false
    display_annotations: true,
    display_faces: true
    display_grid: true
    ...
```

Well I would have expected that the second filed ('scene') would be put in block style because it is splitted across multiple lines and thus flow style makes it hard to read.
I think the current implementation is only looking at if a node has children or not in order to decide what style to use. 

I think it could be much better to rely on unsplitted line length: the style falls back to block when it gets over the `width` parameter. Do you think it's an acceptable feature ?
