### ISSUE TITLE
custom representer to create `!!python` tag fails

### ISSUE THREAD

**Issue by allefeld** [yaml/pyyaml#487]
I'm trying to create a representer that writes numpy arrays in a nicer, human-readable format.

For example, when I dump the array created with `numpy.array([[1, 2, 3], [4.5, 6.7, 8.9]])` I get

````yaml
!!python/object/apply:numpy.core.multiarray._reconstruct
args:
- !!python/name:numpy.ndarray ''
- !!python/tuple
  - 0
- !!binary |
  Yg==
state: !!python/tuple
- 1
- !!python/tuple
  - 2
  - 3
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- false
- !!binary |
  AAAAAAAA8D8AAAAAAAAAQAAAAAAAAAhAAAAAAAAAEkDNzMzMzMwaQM3MzMzMzCFA
````

which is very complicated and not human-readable.

This array can equivalently be represented by

````yaml
!!python/object/apply:numpy.array
args:
- - [1.0, 2.0, 3.0]
  - [4.5, 6.7, 8.9]
- float64
````

and still be readable by PyYAML *without a special constructor function* – important for sharing data –, by calling the `numpy.array` function.

I wrote a representer to create such YAML code:

````python
def ndarray_representer(dumper, array):
    return dumper.represent_mapping(
        '!!python/object/apply:numpy.array',
        {'args': [array.tolist(), str(array.dtype)]})

yaml.add_representer(numpy.ndarray, ndarray_representer)
````

Unfortunately, the result of `yaml.dump(array, default_flow_style=None)` is

````
!%21python/object/apply:numpy.array
args:
- - [1.0, 2.0, 3.0]
  - [4.5, 6.7, 8.9]
- float64
````

i.e. I get `!%21` instead of `!!` at the beginning of the tag.

Is that a bug? How can I fix it?
