### ISSUE TITLE
Load line in YAML file containing custom Tag?

### ISSUE THREAD

**Issue by holec** [yaml/pyyaml#537]
Hello, 

I have the following YAML file which is used by a third party tool. 

```
timezone: "Europe/Zurich"

_export:
  py:
    python: ${virtualenv_home}/bin/python3
  log_level: INFO
  poll_interval: 1
  workflow_name: test_workflow

!include : 'params.yml'

+say_hello:
  echo>: Hello world!
```

My goal is to load this YAML file change a few things and then dump it into a file.
This would work just fine if that "!include<space>:<space> 'params.yml'" wouldn't be.

How would I load this line so if it gets dumped back into a file it looks the same way it does now "!include : 'params.yml'?
The actual including will be handled by the third-party tool.

I played around with different loaders/constructors but never got the right results. 
```
null: params.yml

```

or

```
? ''    
 :  params.yml 
```

or 
```
!include '' : params.yml
```
Thank you
