### ISSUE TITLE
how can load a yaml file within quotation

### ISSUE THREAD

**Issue by yangllty** [yaml/pyyaml#593]
this yaml file is just like that:
```yaml
defaults: &defaults
  adapter:  postgres
  host:     localhost

development:
  database: myapp_development
  <<: *defaults

```
how can i load this file?
