### ISSUE TITLE
Module fails to properly parse .yml file

### ISSUE THREAD

**Issue by nivedvenugopalan** [yaml/pyyaml#633]
I'm working on a project that requires editing `.yml` files. It does not produce any error, but fails to properly parse the `.yml`

**CODE**
```python
import yaml
from pprint import PrettyPrinter
pp = PrettyPrinter(indent=4)

with open(r".\data\nlu.yml", "r") as f:
    yaml_file = yaml.load(f, Loader=yaml.FullLoader)
    pp.pprint(yaml_file)
```

**RAW YML FILE DATA:**
```yaml
version: "3.1"

nlu:
- intent: greet
  examples: |
    - hey
    - hello
    - hi
    - hello there
    - good morning
    - good evening
    - moin
    - hey there
    - let's go
    - hey dude
    - goodmorning
    - goodevening
    - good afternoon

- intent: goodbye
  examples: |
    - cu
    - good by
    - cee you later
    - good night
    - bye
    - goodbye
    - have a nice day
    - see you around
    - bye bye
    - see you later

- intent: affirm
  examples: |
    - yes
    - y
    - indeed
    - of course
    - that sounds good
    - correct

- intent: deny
  examples: |
    - no
    - n
    - never
    - I don't think so
    - don't like that
    - no way
    - not really

- intent: mood_great
  examples: |
    - perfect
    - great
    - amazing
    - feeling like a king
    - wonderful
    - I am feeling very good
    - I am great
    - I am amazing
    - I am going to save the world
    - super stoked
    - extremely good
    - so so perfect
    - so good
    - so perfect

- intent: mood_unhappy
  examples: |
    - my day was horrible
    - I am sad
    - I don't feel very well
    - I am disappointed
    - super sad
    - I'm so sad
    - sad
    - very sad
    - unhappy
    - not good
    - not very good
    - extremly sad
    - so saad
    - so sad

- intent: bot_challenge
  examples: |
    - are you a bot?
    - are you a human?
    - am I talking to a bot?
    - am I talking to a human?
```
**OUTPUT WHEN PARSED (printed using `pprint`):**
```python
{   'nlu': [   {   'examples': '- hey\n'
                               '- hello\n'
                               '- hi\n'
                               '- hello there\n'
                               '- good morning\n'
                               '- good evening\n'
                               '- moin\n'
                               '- hey there\n'
                               "- let's go\n"
                               '- hey dude\n'
                               '- goodmorning\n'
                               '- goodevening\n'
                               '- good afternoon\n',
                   'intent': 'greet'},
               {   'examples': '- cu\n'
                               '- good by\n'
                               '- cee you later\n'
                               '- good night\n'
                               '- bye\n'
                               '- goodbye\n'
                               '- have a nice day\n'
                               '- see you around\n'
                               '- bye bye\n'
                               '- see you later\n',
                   'intent': 'goodbye'},
               {   'examples': '- yes\n'
                               '- y\n'
    'version': '3.1'}
```

**Comment by perlpunk** [comment]
The code works fine here, when I run it.
Your output looks incomplete (missing comma before the last line), so it rather seems to be a problem with PrettyPrinter or your terminal.
Try to reduce your problem. What's your python version, what's your PyYAML version, what's your PrettyPrinter version, what platform are you running this on?

**Comment by nivedvenugopalan** [comment]
I re-ran the code without pretty print; It still has the same error. 

code: 
```python
import yaml

with open(r".\data\nlu.yml", "r") as f:
    yaml_file = yaml.load(f, Loader=yaml.FullLoader)
    print(yaml_file)
```

output (i have copied the whole terminal): 
```
(venv) PS E:\assistant\src> & e:/assistant/venv/Scripts/python.exe e:/assistant/src/web_interface/yamleditor.py
{'version': '3.1', 'nlu': [{'intent': 'greet', 'examples': "- hey\n- hello\n- hi\n- hello there\n- good morning\n- good evening\n- moin\n- hey there\n- let's go\n- hey dude\n- goodmorning\n- goodevening\n- good afternoon\n"}, {'intent': 'goodbye', 'examples': '- cu\n- good by\n- cee you later\n- good night\n- bye\n- goodbye\n- have a nice day\n- see you around\n- bye bye\n- see you later\n'}, {'intent': 'affirm', 'examples': '- yes\n- y\n- indeed\n- of course\n- that sounds good\n- correct\n'}, {'intent': 'deny', 'examples': "- no\n- n\n- never\n- I don't think so\n- don't like that\n- no way\n- not really\n"}, {'intent': 'mood_great', 'examples': '- perfect\n- great\n- amazing\n- feeling like a king\n- wonderful\n- I am feeling very good\n- I am great\n- I am amazing\n- I am going to save the world\n- super stoked\n- extremely good\n- so so perfect\n- so good\n- so perfect\n'}, {'intent': 'mood_unhappy', 'examples': "- my day was horrible\n- I am sad\n- I don't feel very well\n- I am disappointed\n- super sad\n- I'm so sad\n- sad\n- very sad\n- unhappy\n- not good\n- not very good\n- extremly sad\n- so saad\n- so sad\n"}, {'intent': 'bot_challenge', 'examples': '- are you a bot?\n- are you a human?\n- am I talking to a bot?\n- am I talking to a human?\n'}]}
(venv) PS E:\assistant\src> 
```

**Comment by perlpunk** [comment]
What "error" are you referrintg to? I cannot see an error.
I also asked you to reduce your example and share some information about your system.
Noone here gets paid to help you.

**Comment by nivedvenugopalan** [comment]
> What "error" are you referrintg to? I cannot see an error. I also asked you to reduce your example and share some information about your system. Noone here gets paid to help you.

Reduced Input and Output, (With the same code as before):
INPUT:
```yaml
version: "3.1"

nlu:
test_words: |
  - hello
  - goodbye
  - i am a bot
  - i hope this works

test_words: |
  - hello
  - goodbye
  - i am a bot
  - i hope this works
```
OUTPUT WHEN PRINTED:
```python
{'version': '3.1', 'nlu': None, 'test_words': '- hello\n- goodbye\n- i am a bot\n- i hope this works'}
```
OUTPUT WHEN DUMPED:
```yaml
nlu: null
test_words: '- hello

  - goodbye

  - i am a bot

  - i hope this works'
version: '3.1'

```

The string have a `-` and `\n` added to them, which can be parsed out. But when dumping the file, it fails to produce the original file, and omits the `|` symbols after the `examples:`. Also as you can see, the output file completely transformed.

### System Info:
- Python Version: Python 3.9.7
- PyYAML Version: 6.0
- I have not used `prettyprinter` in these examples
- Running these on local vscode, 

Sorry I was in a rush, and didn't read the whole reply.
