### ISSUE TITLE
Loading in a yaml changes keys to alphabetical order (mapping issue)

### ISSUE THREAD

**Issue by Castisho** [yaml/pyyaml#636]
I am trying to use pyyaml to read an already existing file, update it and then dump it back into the existing file. However, upon loading it, the keys are reordered into alphabetical order. I read some people saying this changed on python 3.6 and up but that hasn't been the case for me.
Example: This is the yaml I'm loading
```
d1:
  e2:
    a3: foo
    b3: bar
  c2:
    a3: foo
    b3: bar
  p2:
    a3: foo
    b3: bar
c1:
  e2:
    a3: foo
    b3: bar
  c2:
    a3: foo
    b3: bar
  p2:
    a3: foo
    b3: bar
e1:
  e2:
    a3: foo
    b3: bar
  c2:
    a3: foo
    b3: bar
  p2:
    a3: foo
    b3: bar
```

And the way I'm opening it is:
```
import yaml, os
from pprintpp import pprint as pp

def opener():
  with open(os.path.expanduser('test.yaml'),'r') as file:
    test = yaml.load(file, Loader=yaml.Loader)

  pp(test)

if __name__ == '__main__':
  opener()
```

The output then looks like this:
```
{
    'c1': {
        'c2': {'a3': 'foo', 'b3': 'bar'},
        'e2': {'a3': 'foo', 'b3': 'bar'},
        'p2': {'a3': 'foo', 'b3': 'bar'},
    },
    'd1': {
        'c2': {'a3': 'foo', 'b3': 'bar'},
        'e2': {'a3': 'foo', 'b3': 'bar'},
        'p2': {'a3': 'foo', 'b3': 'bar'},
    },
    'e1': {
        'c2': {'a3': 'foo', 'b3': 'bar'},
        'e2': {'a3': 'foo', 'b3': 'bar'},
        'p2': {'a3': 'foo', 'b3': 'bar'},
    },
}
```
As you can see on every level the keys are reordered into alphabetical order.

Does anyone know if there's a way to avoid these key changes, my work is dependent on the original key order.
These are the versions I'm working with:
`PyYAML 6.0`
`Python 3.9.10`
