### ISSUE TITLE
CSafeLoader fails cannot handle bad quoting

### ISSUE THREAD

**Issue by RoboMagus** [yaml/pyyaml#655]
Related issue in Home Assistant: home-assistant/core#75374

when attempting to load the following yaml snippet using `SafeLoader`, a useful error is returned that indicates what is wrong. However when attempting to parse with `CSafeLoader` nothing is returned (in Home Assistant).
```yaml
automation:
- id: '1658085239190'
  alias: Config validation test
  description: ''
  trigger:
  - platform: time
    at: 00:02:03
  condition: []
  action:
  - service: script.notify_admin
    data:
      # 3 quotes here are not caught at all!
      title: 'Here's something that does not work...!'
      message: failing
  mode: single
```

When attempting to replicate from within a standalone Python environment, the following error is thrown:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: type object 'CSafeLoader' has no attribute 'load'
```
Instead of something helpful.
