### ISSUE TITLE
Variable Substitution in YAML not performed before loading into Python

### ISSUE THREAD

**Issue by Montana** [yaml/pyyaml#668]
See the following:

```yml
vars:
  version: 0.0.1
  path:
    train: ./data/for-training-cnn
    test: ./data/for-testing-cnn
    model: "./data/model/sandbox"
test: ${vars.path.model}
```
The `YAML` file:

```python
import yaml
from yaml import Loader

config = yaml.load(open("this.yml"), Loader=Loader)
print(config['test']) # Output -> "${vars.path.model}" not "./data/model/sandbox"
```

Shouldn't `config['test']` contain `./data/model/sandbox`, not `${vars.path.model}`. Why isn't the variable being substituted?

**Comment by Ark-kun** [comment]
I'm not sure that such template substitution is part of the YAML specification.

You can use the YAML syntax to define and use references:

```yaml
vars:
  version: 0.0.1
  path:
    train: ./data/for-training-cnn
    test: ./data/for-testing-cnn
    model: &vars_path_model "./data/model/sandbox"
test: *vars_path_model 
```
