### ISSUE TITLE
issues reading lines containing specific regex

### ISSUE THREAD

**Issue by The-Judge** [yaml/pyyaml#680]
Hi everyone,

I am using [yamllint](https://yamllint.readthedocs.io/en/stable/) to validate the YAML structure of my Ansible Codebase.

In my Ansible code, there is the following task:

```
- name: set basic parameters in debconf
  shell:
    cmd: "echo '{{ debconf_param }} {{ debconf_value }}' | debconf-set-selections"
  no_log: "{{ no_log_|default('yes')|bool }}"
  when:
    - "( debconf_current_value.stdout | regex_replace('[\r\n\t\f\v  ]+', ' ') ) != ( debconf_param + ' ' + debconf_value )"
```

The first parameter of `regex_replace` causes the following error raised by PyYAML:

```
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 33, in <module>
    sys.exit(load_entry_point('yamllint==1.28.0', 'console_scripts', 'yamllint')())
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/cli.py", line 221, in run
    prob_level = show_problems(problems, file, args_format=args.format,
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/cli.py", line 114, in show_problems
    for problem in problems:
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/linter.py", line 199, in _run
    for problem in get_cosmetic_problems(buffer, conf, filepath):
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/linter.py", line 136, in get_cosmetic_problems
    for problem in rule.check(rule_conf,
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/rules/quoted_strings.py", line 264, in check
    not _quotes_are_needed(token.value)):
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/rules/quoted_strings.py", line 190, in _quotes_are_needed
    loader = yaml.BaseLoader('key: ' + string)
  File "/usr/local/opt/pyyaml/lib/python3.10/site-packages/yaml/loader.py", line 14, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/opt/pyyaml/lib/python3.10/site-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/opt/pyyaml/lib/python3.10/site-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x000c: special characters are not allowed
  in "<unicode string>", position 57
```

**Comment by perlpunk** [comment]
I cannot reproduce that.
I can reproduce the error when I create a file with a 000c character, though. It's a form feed.
Is that really your input file? where's the 000c character? I don't see it with hexdump. Maybe you lost it when copying and pasting.
Anyway, such characters are not allowed in YAML and must be escaped (and you already have a `\f` there).

**Comment by The-Judge** [comment]
... thank you for your fast answer and sorry for my late reply! After your reply, I had to investigate a bit more in that direction and now, I am completely puzzled. Without further intro, let me show you why:

I changed the original example file by adding a `line-length` disable line; it now looks like this:

```
---
# yamllint disable rule:line-length

# Takes:
#  - debconf_param
#  - debconf_value

- name: "get debconf parameter for {{ debconf_param }}"
  shell:
    cmd: "debconf-get-selections | grep '{{ debconf_param.split(' ')[1] }}'"
  no_log: "{{ no_log_|default('yes')|bool }}"
  register: debconf_current_value
  changed_when: false
  failed_when: debconf_current_value.rc not in [ 0, 1 ]

- name: set basic parameters in debconf
  shell:
    cmd: "echo '{{ debconf_param }} {{ debconf_value }}' | debconf-set-selections"
  no_log: "{{ no_log_|default('yes')|bool }}"
  when:
    - "( debconf_current_value.stdout | regex_replace('[\r\n\t\f\v  ]+', ' ') ) != ( debconf_param + ' ' + debconf_value )"

...
```

And now, let me show what I found:
No matter how stupid this sounds, it looks like it depends somehow on the directory or other files that are checked if this happens or not! Let me show you what I mean:

I copied the file to a separate folder on my desktop, where nothing else is. There, it works:
```
680 $ pwd
/Users/mrichter/Desktop/680
680 $ ls -al
total 4
drwxr-xr-x   3 mrichter staff  96 Dec  2 10:03 .
drwx------+ 27 mrichter staff 864 Dec  2 09:59 ..
-rw-r--r--   1 mrichter staff 705 Dec  2 10:03 debconf_change_selections.yml
680 $ yamllint .
680 $
```

But even if the file is checksum-identical in my Ansible folder, there it breaks:
```
ansible $ md5sum ./roles/openldap/tasks/debconf_change_selections.yml ~/Desktop/680/debconf_change_selections.yml
9abfb4e0dbacbed62a1f7d3eecc97c48  ./roles/openldap/tasks/debconf_change_selections.yml
9abfb4e0dbacbed62a1f7d3eecc97c48  /Users/mrichter/Desktop/680/debconf_change_selections.yml
ansible $ cat .yamlignore
# yamllint has issues with "regex_replace('[\r\n\t\f\v  ]+', ' ')", resulting in:
# yaml.reader.ReaderError: unacceptable character #x000c: special characters are not allowed
# See https://github.com/yaml/pyyaml/issues/680
#roles/openldap/tasks/debconf_change_selections.yml
ansible $ cat .yamllint
---
yaml-files:
  - '*.yml'
  - '*.yaml'
  - '*.yamllint'

rules:
  braces:
    level: error
    max-spaces-inside: 1
  brackets:
    level: error
    max-spaces-inside: 1
  colons:
    level: error
  commas:
    level: error
    min-spaces-after: 0
  comments:
    level: error
    require-starting-space: false
  comments-indentation:
    level: error
  document-end:
    level: error
  document-start:
    level: error
  empty-lines:
    level: error
  empty-values:
    level: error
  float-values:
    level: error
  hyphens:
    level: error
  indentation:
    level: error
  key-duplicates:
    level: error
  new-line-at-end-of-file:
    level: error
  new-lines:
    level: error
  octal-values:
    level: error
  quoted-strings:
    level: error
    required: only-when-needed
    # Allow quoted strings for strings containing:
    #
    # - Curly braces, since Ansible uses CBs for variable utilization and requires them
    #   to be quoted
    # - '^', '$', '.*' and '+', since these often indicate that this is a regex, which
    #   can be tricky to escape and we do not want the linter cause extra-efforts to
    #   circumvent these edge-cases.
    #
    extra-allowed: ['^.*({|}).*$', '(\^|\$|\.\*|\+)']
  trailing-spaces:
    level: error
  truthy:
    level: error
    allowed-values: ['true', 'false', 'yes', 'no']

ignore-from-file: [.gitignore, .yamlignore]
...
ansible $ cat .gitignore
ansible.merged.cfg
.vault
.idea/
.python-version
**/Vagrantfile
**/.vagrant/
**/virtual_envs/*
!**/virtual_envs/.keep
**/.venv
playbooks/TEST.yml
roles/test/
ansible $ yamllint .
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 33, in <module>
    sys.exit(load_entry_point('yamllint==1.28.0', 'console_scripts', 'yamllint')())
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/cli.py", line 221, in run
    prob_level = show_problems(problems, file, args_format=args.format,
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/cli.py", line 114, in show_problems
    for problem in problems:
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/linter.py", line 199, in _run
    for problem in get_cosmetic_problems(buffer, conf, filepath):
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/linter.py", line 136, in get_cosmetic_problems
    for problem in rule.check(rule_conf,
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/rules/quoted_strings.py", line 264, in check
    not _quotes_are_needed(token.value)):
  File "/usr/local/Cellar/yamllint/1.28.0/libexec/lib/python3.10/site-packages/yamllint/rules/quoted_strings.py", line 190, in _quotes_are_needed
    loader = yaml.BaseLoader('key: ' + string)
  File "/usr/local/opt/pyyaml/lib/python3.10/site-packages/yaml/loader.py", line 14, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/opt/pyyaml/lib/python3.10/site-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/local/opt/pyyaml/lib/python3.10/site-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x000c: special characters are not allowed
  in "<unicode string>", position 57
ansible $ echo roles/openldap/tasks/debconf_change_selections.yml >> .yamlignore
ansible $ yamllint .
ansible $
```

I have no idea what's going on there O.o
