### ISSUE TITLE
Optional keys

### ISSUE THREAD

**Issue by sebastianzander** [yaml/pyyaml#684]
Hi, I could not find anything in the documentation regarding optional keys. I am extending code from a colleague who isn't available for some time. Our script uses the following calls to `add_path_resolver` to associate two python classes with the given tags. The general purpose of our script is to convert a formal definition of types in the YAML format to a C++ API.

```python
yaml.add_path_resolver("!attributes", ["attributes", None])
yaml.add_path_resolver("!attributes", ["attributes", None, "compound", None])
yaml.add_path_resolver("!type", [])
```

The two python classes both have a `from_yaml` method:

```python
@classmethod
    def from_yaml(cls, loader: yaml.FullLoader, node):
        data = loader.construct_mapping(node, deep=True)
        return cls(**data)
```

A typical YAML file that will be parsed looks like this:

```yaml
---
name: SignalData
attributes:
- name: startNode
  reference: Node
- name: signalNode
  reference: Node
- name: flags
  type: int
...
```

With our script in its current state it is not possible to have an optional key `plural` like so:

```yaml
---
name: SignalData
plural: SignalData # shall be optionally specified, in cases where regular pluralization or simply appending an 's' does not work
attributes:
...
```

I added `self._plural` to the python class, tried to understand the second argument to `add_path_resolver` and experimented with it, but I don't get it to work that the key `plural` is allowed to be optional and `self._plural` be default constructed/initialized.

I am thankful for any help.
