### ISSUE TITLE
Handle top level yaml property `on`

### ISSUE THREAD

**Issue by wsams** [yaml/pyyaml#696]
A document containing a top-level key named `on` is rendered as a boolean value instead of the literal string `on` when loading and dumping a document.

For example,

```
import yaml

tmpl = """on:
  push:
    branches: [ main ]
"""

print(yaml.dump(yaml.load(tmpl, Loader=yaml.Loader)))
```

will output,

```
true:
  push:
    branches:
    - main
```

I would expect,

```
on:
  push:
    branches:
    - main
```

but the word `on` is replaced with a boolean value `true`.

I'm using `pyyaml==6.0` with Python 3.10.9.
