### ISSUE TITLE
yaml.safeload() is not reading values correctly.

### ISSUE THREAD

**Issue by KiranPaladugu** [yaml/pyyaml#697]
When loading the yaml data, yaml.safe_load() returns incorrect data.

```
data: 
- type: 4
  details:
    name: 0000:03:00.0
```

yaml.safe_load() returns, the element name value is incorrect

```
data:
- details:
    name: 180.0
  type: 4
```

PyYaml version 6.0
