### ISSUE TITLE
Inconsistent/Wrong Type casting when using yaml.dump/safe_dump

### ISSUE THREAD

**Issue by stuartornum** [yaml/pyyaml#794]
Hi,

Think I've found an issue when using yaml.dump and safe_dump. (Using pyyaml v6.0.1)

import yaml

```
data = {
    "buildings": [
        {
            "building_id": "0000007",
            "building_name": "100 central square"
        },{
            "building_id": "0000008",
            "building_name": "Headquarters"
        },{
            "building_id": "0000009",
            "building_name": "Test"
        },{
            "building_id": "0000010",
            "building_name": "London House"
        },
    ]
}

print(yaml.dump(data))
```

## The output

Notice 0000008 and 0000009 are not strings, like the others.

```
buildings:
- building_id: '0000007'
  building_name: 100 central square
- building_id: 0000008
  building_name: Headquarters
- building_id: 0000009
  building_name: Test
- building_id: '0000010'
  building_name: London House
```
